name: Tsan Check

env:
  UBUNTU_CLANG_VERSION: clang++-15

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'Docs/**'
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'Docs/**'
      - '**.md'

jobs:
  linux_clang:
    runs-on: ubuntu-latest
    name: Linux Clang Tsan Check

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Configure CMake
      working-directory: ${{github.workspace}}/Build
      run: ./cmake_linux_clang_gcc.sh RelWithDebInfo ${{env.UBUNTU_CLANG_VERSION}} \
        -DCMAKE_CXX_FLAGS="-fsanitize=thread" \
        -DCROSS_PLATFORM_DETERMINISTIC=OFF \
        -DTARGET_VIEWER=OFF \
        -DTARGET_SAMPLES=OFF \
        -DTARGET_HELLO_WORLD=OFF \
        -DTARGET_UNIT_TESTS=ON \
        -DTARGET_PERFORMANCE_TEST=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/Build/Linux_RelWithDebInfo -j $(nproc)

    - name: Unit Tests
      working-directory: ${{github.workspace}}/Build/Linux_RelWithDebInfo
      run: ctest --output-on-failure --verbose
    - name: Test ConvexVsMesh
      working-directory: ${{github.workspace}}/Build/Linux_RelWithDebInfo
      run: ./PerformanceTest -q=LinearCast -t=max -s=ConvexVsMesh
    - name: Test Ragdoll
      working-directory: ${{github.workspace}}/Build/Linux_RelWithDebInfo
      run: ./PerformanceTest -q=LinearCast -t=max -s=Ragdoll
